Fix expandable view cell overdraw
Sovcombank/SpreadsheetView pull request #6
Opened 2019-10-24 08:49 UTC by ColonelCheese

2019-11-25 07:31 UTC, alexander-gladyshev requested changes

2019-11-25 07:31 UTC, alexander-gladyshev commented on Framework/Sources/LayoutEngineExpandable.swift
> +//        guard subcellOrigin.y + subrowOffsetY > visibleRect.minY else {
необходимо не отрисовывать ячейки вне границ графика

2019-11-25 07:31 UTC, alexander-gladyshev commented on Framework/Sources/LayoutEngineExpandable.swift
> +//    let indexPath = SubrowIndexPath(indexPath: IndexPath(row: address.rowIndex, column: address.columnIndex), subrow: address.subrow)
убрать ненужный код

2019-11-26 08:11 UTC, ColonelCheese commented on Framework/Sources/LayoutEngineExpandable.swift
> +//        guard subcellOrigin.y + subrowOffsetY > visibleRect.minY else {
@alexander-gladyshev  исправлено https://github.com/Sovcombank/SpreadsheetView/pull/6/commits/dfe199992014a8bb1ed8e1ab430f2d2a48983ad8

2019-11-26 08:15 UTC, ColonelCheese commented on Framework/Sources/LayoutEngineExpandable.swift
> +//    let indexPath = SubrowIndexPath(indexPath: IndexPath(row: address.rowIndex, column: address.columnIndex), subrow: address.subrow)
@alexander-gladyshev исправил https://github.com/Sovcombank/SpreadsheetView/pull/6/commits/2891bf478b36c027a39127ca008687e012d53c5e

2019-11-26 08:40 UTC, merged